version: '3.8'

services:

  redis:
    image: "redis:latest"
    container_name: "apiGateway_redis"
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - MSA-network

volumes:
  redis_data:

networks:
 MSA-network:
    external: true
