version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: customer_service_container
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - eureka-network

  redis:
    image: "redis:latest"
    container_name: "customer_service_redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - eureka-network

volumes:
  mysql_data:
  redis_data:

networks:
  eureka-network:
    driver: bridge
