services:
  # API Gateway
  apigateway_redis:
    image: "redis:latest"
    container_name: "apiGateway_redis"
    ports:
      - "6380:6379"
    volumes:
      - apigateway_redis_data:/data
    networks:
      - MSA-network

  # Eureka Server
  eureka-server:
    image: eureka-eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - MSA-network

  # Customer Service
  customer_mysql:
    image: mysql:latest
    container_name: customer_service_container
    env_file:
      - ./customer-service/.env
    ports:
      - "3307:3306"
    volumes:
      - customer_mysql_data:/var/lib/mysql
    networks:
      - MSA-network

  customer_redis:
    image: "redis:latest"
    container_name: "customer_service_redis"
    ports:
      - "6379:6379"
    volumes:
      - customer_redis_data:/data
    networks:
      - MSA-network

  # Product Service
  product_mysql:
    image: mysql:latest
    container_name: product_service_container
    env_file:
      - ./product-service/.env
    ports:
      - "3308:3306"
    volumes:
      - product_mysql_data:/var/lib/mysql
    networks:
      - MSA-network

  product_redis:
    image: "redis:latest"
    container_name: "product_stock_redis"
    ports:
      - "6381:6379"
    volumes:
      - product_redis_data:/data
    networks:
      - MSA-network

  # Order Service
  order_mysql:
    image: mysql:latest
    container_name: order_service_container
    env_file:
      - ./order-service/.env
    ports:
      - "3309:3306"
    volumes:
      - order_mysql_data:/var/lib/mysql
    networks:
      - MSA-network

  order_redis:
    image: redis:latest
    container_name: order_service_redis
    ports:
      - 6382:6379
    volumes:
      - order_redis_data:/data
    networks:
      - MSA-network

  # Payment Service
  payment_mysql:
    image: mysql:latest
    container_name: payment_service_container
    env_file:
      - ./payment-service/.env
    ports:
      - "3310:3306"
    volumes:
      - payment_mysql_data:/var/lib/mysql
    networks:
      - MSA-network

volumes:
  apigateway_redis_data:
  customer_mysql_data:
  customer_redis_data:
  product_mysql_data:
  product_redis_data:
  order_mysql_data:
  order_redis_data:
  payment_mysql_data:

networks:
  MSA-network:
    name: MSA-network
    driver: bridge