version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: product_service_container
    env_file:
      - .env
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
