version: '3.8'

services:
  api-gateway:
    build:
      context: .
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - eureka-network

networks:
  eureka-network:
    external: true
