version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: user_service_container
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  redis:
    image: "redis:latest"
    container_name: "user_service_redis"
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

volumes:
  mysql_data:
  redis_data:

networks:
  my_network:
    driver: bridge
