server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test-order-service
          uri: lb://order-service
          predicates:
            - Path=/api/test/time-orders/**

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**, /api/wishlist/**
      default-filters:
        - name: ApiGatewayFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true


jwt:
  header: Authorization
  secret:
    key: ${JWT_SECRET_KEY}
  refresh:
    secret:
      key: ${JWT_REFRESH_SECRET_KEY}
  expiration_time: 6000
  refresh_expiration_time: 604800

#logging:
#  level:
#    org.springframework.cloud.gateway: trace
#    org.springframework: debug
#    reactor.netty.http.client: debug



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
