server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
      default-filters:
        - name: ApiGatewayFilter


jwt:
  header: Authorization
  secret:
    key: ${JWT_SECRET_KEY}
  refresh:
    secret:
      key: ${JWT_REFRESH_SECRET_KEY}
  expiration_time: 6000
  refresh_expiration_time: 604800

logging:
  level:
    org.springframework.security: debug
    org.springframework: debug
    org.springframework.JwtTokenUtil: debug
    org.springframework.ApiGatewayFilter: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
