server:
  port: 8083
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://order_service_container:3306/order_database
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  header: Authorization
  secret:
    key: ${JWT_SECRET_KEY}
  refresh:
    secret:
      key: ${JWT_REFRESH_SECRET_KEY}
  expiration_time: 3600
  refresh_expiration_time: 604800
logging:
    level:
      org.springframework.security: debug
#      org.springframework: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'